project:
  type: book
  output-dir: docs

book:
  title: "ICAO EUR Doc 030 - Performance Monitoring - 2023"
  author: "Doc 030 Guidance Material Task Force"
  date: today
  output-file: "ICAO-Doc30-Monitoring"
  chapters:
    - index.qmd
    - 01-intro.qmd
  #  - summary.qmd
    - 99-references.qmd
  downloads: [pdf]

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreport