project:
  type: book
  output-dir: docs

book:
  title: "ICAO Doc30 - Performance Monitoring"
  author: "Doc30 Guidance Material Task Force"
  date: today
  output-file: "ICAO-Doc30-Monitoring"
  chapters:
    - index.qmd
    - 01-intro.qmd
  #  - summary.qmd
    - 90-references.qmd
  downloads: [pdf]

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreport